name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    permissions:
      contents: read
      actions: write
    uses: stevenfackley/gh-actions/.github/workflows/ci-gradle.yml@v1
    with:
      project-name: GhostCrab
      runs-on: '["self-hosted","macOS","ARM64"]'
      java-version: "17"
      test-task: testDebugUnitTest
      run-lint: true
      run-detekt: true
      extra-gradle-args: --no-configuration-cache
      report-path: app/build/reports
      build-release: true
    secrets: inherit
